### ISSUE TITLE
Unable to run scripts/00_virtual.sh on centos 8 jumpbox  

### ISSUE THREAD

**Issue by tosin2013** [karmab/kcli-openshift4-baremetal#115]
I am currently getting the error below when I attempt to run the 00_virtual.sh script after the kcli plan. 

**I performed the following steps**
```
vim openshift_pull.json
cd $HOME
git clone https://github.com/karmab/kcli-openshift4-baremetal
cd kcli-openshift4-baremetal

kcli create plan --paramfile lab.yml lab

kcli ssh  lab-installer
sudo su - root

scripts/00_virtual.sh
```

**Error message** 
```
Complete!
Traceback (most recent call last):
  File "/usr/bin/kcli", line 11, in <module>
    load_entry_point('kcli==99.0', 'console_scripts', 'kcli')()
  File "/usr/lib/python3.6/site-packages/kvirt/cli.py", line 5162, in cli
    args.func(args)
  File "/usr/lib/python3.6/site-packages/kvirt/cli.py", line 3398, in create_sushy
    baseconfig = Kbaseconfig(client=args.client, debug=args.debug, offline=True)
  File "/usr/lib/python3.6/site-packages/kvirt/baseconfig.py", line 344, in __init__
    if self.host.startswith('http'):
AttributeError: 'NoneType' object has no attribute 'startswith'
[root@lab-installer ~]# cat /etc/redhat-release
CentOS Stream release 8
```

**Comment by karmab** [comment]
can you share /root/.kcli/config.yml on the vm?
